# Vi keys in copy mode (prefix + [)
set-w -g mode-keys vi

# Terminal type inside tmux
set -g default-terminal "tmux-256color"

# Eliminate Esc key delay in Vim
set -sg escape-time 10

# Mouse support
set -g mouse on
